# This workflow will deploy the API using AWS Amplify

name: Deploy Dev API

on:
  push:
    branches: [develop]
    paths: [amplify/**]
  workflow_dispatch: {}

jobs:
  build_test:
    name: Build and Test
    uses: ./.github/workflows/deploy-ci.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  deploy:
    name: Deploy
    uses: ./.github/workflows/reusable-deploy.yml
    needs: build_test
    with:
      amplify_env: dev
      amplify_appId: d5u222qsuh3lu
      branch_ref: develop
      deployment_env: Develop
      deployment_url: https://graphqlapi-dev.slashkudos.com/graphql
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
