# This workflow will deploy the API using AWS Amplify

name: Deploy Production API

on:
  push:
    branches: [main]
    paths: [amplify/**]
  workflow_dispatch:

jobs:
  build_test:
    name: Build and Test
    uses: ./.github/workflows/deploy-ci.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  deploy:
    name: Deploy
    uses: ./.github/workflows/reusable-deploy.yml
    needs: build_test
    with:
      amplify_env: prod
      amplify_appId: d5u222qsuh3lu
      branch_ref: main
      deployment_env: Production
      deployment_url: https://graphqlapi.slashkudos.com/graphql
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
