# This workflow will deploy the API using AWS Amplify

name: Deploy Dev API

on:
  push:
    branches: [develop]
    paths: [amplify/**]
  workflow_call:
    inputs:
      force:
        description: "Force push to AWS"
        default: false
        required: false
        type: boolean
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
  workflow_dispatch:
    inputs:
      force:
        description: "Force push to AWS"
        default: false
        required: false
        type: boolean

jobs:
  build_test:
    name: Build and Test
    uses: ./.github/workflows/deploy-ci.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build_test
    environment:
      name: Develop
      url: https://graphqlapi-dev.slashkudos.com/graphql
    env:
      amplify_env: dev
      amplify_appId: d5u222qsuh3lu
    concurrency: ${{ github.workflow }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Setup Amplify
        uses: ./.github/workflows/composite/amplify-setup
        with:
          node_version: "16.x"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: amplify pull
        run: ./scripts/amplify_pull.sh ${{ env.amplify_env }} ${{ env.amplify_appId }}
      - name: amplify push
        shell: pwsh
        run: |
          # GraphQL transformer version 2 outputs GraphQL API Key even with "CreateAPIKey": 0
          $shouldForce = "${{ inputs.force }}${{ github.event.inputs.force }}" ? [Convert]::ToBoolean("${{ inputs.force }}${{ github.event.inputs.force }}") : $false
          if($shouldForce) {
            Write-Host "Running amplify push --yes --force"
            amplify push --yes --force | grep -v "GraphQL API KEY"
          }
          else {
            Write-Host "Running amplify push --yes"
            amplify push --yes | grep -v "GraphQL API KEY"
          }
          if(!$?) { throw "Push failed." }
      # TODO - Run integration tests against new deployment
