# This workflow will deploy the API using AWS Amplify

name: Deploy Dev API

on:
  push:
    branches: [develop]
    paths: [amplify/**]
  workflow_call:
    inputs:
      force:
        description: "Force push to AWS"
        default: false
        required: false
        type: boolean
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy Dev
    runs-on: ubuntu-latest
    environment:
      name: Develop
      url: https://graphqlapi-dev.slashkudos.com/graphql
    env:
      amplify_env: dev
      amplify_appId: d5u222qsuh3lu
    concurrency: ${{ github.workflow }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Setup Amplify
        uses: ./.github/workflows/composite/amplify-setup
        with:
          node_version: "16.x"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: amplify pull
        run: ./scripts/amplify_pull.sh ${{ env.amplify_env }} ${{ env.amplify_appId }}
      - name: Run Mock Integration Tests
        run: |
          ./scripts/update_src.sh
          ./clients/typescript/scripts/run_mock_tests.sh
      - name: amplify push
        shell: pwsh
        run: |
          # GraphQL transformer version 2 outputs GraphQL API Key even with "CreateAPIKey": 0
          $shouldForce = "${{ inputs.force }}" ? [Convert]::ToBoolean("${{ inputs.force }}") : $false
          if($shouldForce) {
            Write-Host "Running amplify push --yes --force"
            amplify push --yes --force | grep -v "GraphQL API KEY"
          }
          else {
            Write-Host "Running amplify push --yes"
            amplify push --yes | grep -v "GraphQL API KEY"
          }
      # TODO - Run integration tests against new deployment
