# This workflow will deploy the API using AWS Amplify

name: Deploy Production API

on:
  push:
    branches: [main]
    paths: [amplify/**]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Prod
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://graphqlapi.slashkudos.com/graphql
    env:
      amplify_env: prod
      amplify_appId: d5u222qsuh3lu
    concurrency: ${{ github.workflow }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Setup Amplify
        uses: ./.github/workflows/composite/amplify-setup
        with:
          node_version: "16.x"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: amplify pull
        run: ./scripts/amplify_pull.sh ${{ env.amplify_env }} ${{ env.amplify_appId }}
      - name: Run Mock Integration Tests
        run: |
          ./scripts/update_src.sh
          ./clients/typescript/scripts/run_mock_tests.sh
      - name: amplify push
        run: amplify push --yes
