# This workflow will deploy the API using AWS Amplify

name: Deploy Production API

on:
  push:
    branches: [main]
    paths: [amplify/**]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Prod
    runs-on: ubuntu-latest
    env:
      amplify_env: prod
      amplify_appId: d5u222qsuh3lu
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install Amplify
        shell: bash
        run: |
          node -v
          npm -v
          npm install -g @aws-amplify/cli
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Pull Amplify Environment
        shell: bash
        run: |
          chmod +x ./scripts/amplify_pull.sh
          ./scripts/amplify_pull.sh $amplify_env $amplify_appId
          amplify status
      - name: Amplify Push
        shell: bash
        run: |
          amplify push --yes
