name: npm publish ci
on:
  pull_request: {}
  push:
    branches: [develop]
    paths: [clients/typescript/**]
  workflow_dispatch: {}

defaults:
  run:
    shell: bash
    working-directory: clients/typescript

jobs:
  publish:
    name: npm publish CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      amplify_env: dev
      amplify_appId: d5u222qsuh3lu
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - name: Run unit tests
        run: npm run test:unit
      - name: Setup @aws-amplify/cli
        uses: philip-gai/setup-aws-amplify-cli@v1
          cli_version: "7.6.22"
          node_version: "16.x"
          cache_dependencies: "true"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: amplify pull
        run: ./scripts/amplify_pull.sh ${{ env.amplify_env }} ${{ env.amplify_appId }}
        working-directory: .
      - name: amplify status
        run: amplify status -v | grep -v "GraphQL API KEY"
      - name: Run Mock Integration Tests
        run: |
          ./scripts/update_src.sh
          ./clients/typescript/scripts/run_mock_tests.sh
        working-directory: .
